# Generated by Django 4.1.3 on 2022-12-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plainTextApp', '0002_word_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
